### ISSUE TITLE
"Something strange" is either a mis-named "All Individuals", or something strange is going on

### ISSUE THREAD

**Issue by WValenti** [mathmednet/diverweb-issues#1]
In https://digs.mathmed.org/cohorts/all.
![Screen Shot 2022-02-18 at 4 12 01 PM](https://user-images.githubusercontent.com/3909236/154761860-4b7cc1fd-6532-42e4-bcb0-7cc944bd8330.png)

**Comment by WValenti** [comment]
Stranger still. "something strange" should be the name of a resultSet in the SGID database owned by Tester, but it isn't. So I searched both the fe & be src hierarchies and there is nothing "strange" at all hardcoded.  Strange indeed.

**Comment by Viqsi** [comment]
This reminds me of a bug that I thought had been fixed. "something strange" is a child of "- All Individuals - " that I'd left in there. The backend was returning NULL as "something strange"'s parent, tho, and that interacted with something in the frontend to suppress display of "- All individuals -".

It's working properly for me, anyways...

![image](https://user-images.githubusercontent.com/6570923/154765710-7e4eed19-09ab-46ff-8b6c-3e47706fa92b.png)

**Comment by Viqsi** [comment]
Also, the owner you should be looking for is "testuser", not "tester".

**Comment by WValenti** [comment]
Unable to reproduce.
