### ISSUE TITLE
Compound set operands display as boxes proportionate to their description text even when that is not shown yet

### ISSUE THREAD

**Issue by WValenti** [mathmednet/diverweb-issues#11]
This is not really a bug, but may be a preference.  We should talk about it.

**Comment by Viqsi** [comment]
Some illustrations.

Before expansion:

![Screen Shot 2022-03-09 at 14 27 06](https://user-images.githubusercontent.com/6570923/157516924-49bd0c03-033a-4a38-ab68-5ffccaef075e.png)

After expansion:

![Screen Shot 2022-03-09 at 14 27 52](https://user-images.githubusercontent.com/6570923/157516955-eb4bd84c-13e2-4d82-a3a0-f227c4ce8b27.png)

**Comment by Viqsi** [comment]
Per DW meeting, this is being looked into by Annalisa.

**Comment by iamtheluckyest** [comment]
Resolved with commit 9922819

**Comment by Viqsi** [comment]
Pulled in with mathmednet/diverweb@f4ac9ba and confirmed all OK now. Thanks!
