### ISSUE TITLE
Loss of context when going for details.

### ISSUE THREAD

**Issue by WValenti** [mathmednet/diverweb-issues#14]
Search and pull up a bunch of variables, go for details on one, go back and have nothing left!  Maybe details does a popup so that original search is not lost.  This may be happening many places.

**Comment by Viqsi** [comment]
Popup could be a new tab, or it could be a widget window drawn in the existing viewport. The former is quick but sometimes misleads users. The latter is snazzier and makes it easier to understand what's happening (we're temporarily popping up a detail window) but requires more UX code that probably isn't present yet.

**Comment by WValenti** [comment]
Sherri also mentioned this: "Not able to go back to page with changes/projects saved—have to start from scratch, which becomes cumbersome."

**Comment by Viqsi** [comment]
In discussion with Digital Wave, we were talking about possibly opening detail views in new tabs, or using Local Storage to save searches. The latter would be extra work (and extra hours); the former is a fairly straightforward workaround. So in the interest of expedience, we may just stick to Open New Tabs instead. And possibly add a tooltip to warn users.

**Comment by Viqsi** [comment]
Merged in with mathmednet/diverweb@03f4a8f and looks good. Thanks!
