### ISSUE TITLE
Getting to compare is overly-complicated

### ISSUE THREAD

**Issue by WValenti** [mathmednet/diverweb-issues#15]
Finding compare variables function is difficult, kinda buried.

Search, select variable for details, then you can compare.

Nice to click on first page to get a few variables to compare.

**Comment by Viqsi** [comment]
Sounds like a UX flow issue to me.

IIRC this was mentioned by Linda during a meeting.

**Comment by Viqsi** [comment]
Per meeting with DW this *might* be settled by going through the Variables Catalog (under Project Catalogs).  Further review necessary.

**Comment by Viqsi** [comment]
No feedback has been received indicating that this is an unacceptable approach, and we've told DW we're done, so I'm closing this issue.
