### ISSUE TITLE
Adding multiple variables is sluggish, doesn't leave a trail, and gets multiple identical entries.

### ISSUE THREAD

**Issue by WValenti** [mathmednet/diverweb-issues#16]
Checkmark when clicked changes color and goes away for a while, no feedback.  It's adding the same variable multiple times.

Color change should persist when you select something.

Checking again would deselect.

**Comment by Viqsi** [comment]
Not sure what circumstances under which this occurs. Where are these checkmarks? Variable set creation?

**Comment by WValenti** [comment]
Yes, in variable set creation, I think the chosen item should move back and forth between the "selected" and "available for selection" lists.

**Comment by Viqsi** [comment]
Upon further review, this and #28 are actually the same issue (or at least are the same component). Since that one has more information in it, closing this as a duplicate of same.
