### ISSUE TITLE
Ascertain Pedigrees include/exclude toggle doesn't "stick"

### ISSUE THREAD

**Issue by WValenti** [mathmednet/diverweb-issues#23]
From Sam: "In “Ascertain Pedigrees” > click “constrain”: the include/exclude toggle seems to be broken. It reverts to displaying “include” immediately after I try selecting “exclude”."

**Comment by WValenti** [comment]
I see this in "Include / Exclude" and in "Constrain by family members..." -> "In" choice for selecting the cohort.

**Comment by Viqsi** [comment]
Acknowledged as a bug by Digital Wave, reproduced, and being worked on by Annalisa.

**Comment by iamtheluckyest** [comment]
Resolved with commit 22f6eca

**Comment by Viqsi** [comment]
Pulled in with mathmednet/diverweb@f4ac9ba and confirmed finished. Thanks!
