### ISSUE TITLE
When comparing variables, insufficient visual feedback upon selecting the second variable

### ISSUE THREAD

**Issue by samuelmf1** [mathmednet/diverweb-issues#28]
I haven't been able to compare variables because the site doesn't let me finalize my selection of a second variable. Nothing happens when I try to click the orange check boxes. Also, I agree with something that was brought up in a different thread... it's really hard to find the compare variables tool.

**Comment by WValenti** [comment]
When I did this earlier today, it allowed 2nd & a 3rd variable to be selected, so I suspect that you just click on the 1 or 2 you want and scroll down to see the results.

Yup, just verified. See attached.
![Screen Shot 2022-03-09 at 1 03 11 PM](https://user-images.githubusercontent.com/3909236/157503275-8ea70cd1-a8c4-4e63-9cf6-2f82bc58caaf.png)

**Comment by Viqsi** [comment]
The checkboxes in question darken when clicked on as a sort of "this is what you just clicked" feedback. The state we're hoping for is for that to be a toggle as to whether or not a variable is in the comparison. Right now it's just a "you clicked the button" indicator.

Also noted during the DW meeting: in the variable search results, it would be nice to have the variable you started comparisons with "pre-clicked" (presuming it's in the search results list - which, given the nature of the compare tool, can be expected to be a common case).

**Comment by iamtheluckyest** [comment]
Resolved with commit 36c951b.

The buttons are now context-aware and switch between `+` and `-`, allowing the user to add or remove from comparison.

<img width="1237" alt="Screen Shot 2022-03-17 at 3 56 45 PM" src="https://user-images.githubusercontent.com/19640576/158841250-e268fd99-899b-4f56-a4d5-37ae0ba744f8.png">

**Comment by Viqsi** [comment]
Just adding a screenshot of their current appearance for review:
<img width="1180" alt="Screen Shot 2022-03-17 at 12 13 38" src="https://user-images.githubusercontent.com/6570923/158845735-67abeaf1-2bab-45c0-8b31-f5db961e4b89.png">

I3700 and V406 are being compared; the rest aren't.

**Comment by Viqsi** [comment]
@iamtheluckyest - any updates?

Linda also noticed that this same issue affects the Combine Two Variables and Combine Multiple Variables pages, and those would also have to be fixed in the same fashion. Essentially, this means of operation is expected anyplace we're selecting more than one variable (at no point do we pick a variable more than once).

**Comment by iamtheluckyest** [comment]
Sorry for the radio silence. I think Kesley and Brittany are still discussing, but hopefully I can push something later today.

**Comment by iamtheluckyest** [comment]
Alright! With commit 5519bb9 I updated the icons for Compare Variables, and added this add/remove functionality to Clinical Constructs and Variable Sets. I found a bug with removing variables from Variable Sets and Clinical Constructs, so I fixed that as well.

**Comment by Viqsi** [comment]
Merged in with mathmednet/diverweb@402ddf7 and all looks good to me. Thanks!
