### ISSUE TITLE
"My Cohorts" and "Build New Cohort" have different displays

### ISSUE THREAD

**Issue by Viqsi** [mathmednet/diverweb-issues#29]
The "Build New Cohort" page ("/cohorts/all") shows cohorts as a tree structure:

![Screen Shot 2022-03-09 at 14 23 29](https://user-images.githubusercontent.com/6570923/157516357-904a8ae4-cc04-4ef5-9e0f-48da3b08c782.png)

The "My Cohorts" page ("/cohorts") shows them as a list:

![Screen Shot 2022-03-09 at 14 23 11](https://user-images.githubusercontent.com/6570923/157516319-ecb6c635-26d3-46ca-99d5-32b7cfe3bf6d.png)

This is an odd discrepancy.

**Comment by Viqsi** [comment]
Per meeting with DW: aside from a change of "My Cohorts" to "My Favorite Cohorts", this is likely to stay as is because "My Cohorts" it's supposed to only track user favorites, and so the whole tree structure can't be guaranteed to stay there.

**Comment by Viqsi** [comment]
(for the record: that minor text change is the only reason why this issue remains open; it's otherwise settled.)

**Comment by iamtheluckyest** [comment]
Changed My Cohorts to My Favorite Cohorts in the navigation, in button tooltips, and in confirmation modal with commit af6a244

**Comment by Viqsi** [comment]
The page title and header both still refer to it as "My Cohorts":

![image](https://user-images.githubusercontent.com/6570923/157764056-01849c39-4a4a-4084-afec-4ee37c42ed0c.png)

**Comment by Viqsi** [comment]
I opted to just go ahead and fix it on our end (mathmednet/diverweb@02c2511) since I was able to pretty quickly figure out how. Thanks for the rest!

**Comment by iamtheluckyest** [comment]
Okay, great! Good catch!
