### ISSUE TITLE
Create Custom Variable should have more obvious droplist for blind old testers like me

### ISSUE THREAD

**Issue by WValenti** [mathmednet/diverweb-issues#30]
I literally went for days thinking that there was nothing active under that tab. Yes, I'm blind-ish, but I don't see why we need subitems under this table when we don't for any others.  And if it turns out that we do need subitems, I'd prefer to have a click anywhere on the tab activate the droplist. Sigh.

**Comment by Viqsi** [comment]
At the risk of confirming your "blind old man" status, there's two places where that occurs - Project Catalogs is the other.

Nonetheless, I agree that clicking on the text of that tab should also drop down the menu.

**Comment by iamtheluckyest** [comment]
Resolved with commit a5e82a3. 

The text as well as the icon is now clickable, toggling the dropdown menu.

**Comment by Viqsi** [comment]
Merged with mathmednet/diverweb@03f4a8f and verified OK. Thanks!
